name: deploy-docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-docs:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: autowarefoundation/autoware-github-actions/deploy-docs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: ${{ github.ref_name == github.event.repository.default_branch }}
